### ISSUE TITLE
Possibility to use existing .ovpn file

### ISSUE THREAD

**Issue by isuftin** [dperson/openvpn-client#1]
The VPN service I subscribe to provides their own .ovpn file. Is it possible to refactor this to use that instead of entering a server/user/pass ?

**Comment by dperson** [comment]
The real problem is that most normal '*.ovpn' file is that the user/pass AFAIK (As Far As I Know), can't be provided in it, only a line that says find them in file X. When you start the docker container, it's not interactive, so it can't ask you for them.

If you want to make the change to the '*.ovpn' file manually and the same for creating the username / password file, please feel free. Now with docker 1.6 there is support to make changes (as in the initial docker image creation) on commit. Which allows you to run (as an example):

    docker commit -c="COPY <my_ovpn_file> /vpn/vpn.conf" -c "COPY <my_auth_file> /vpn/vpn.auth" <image-id-for-example: 98bd7fc99854> custom-openvpn

See the creation process in `https://github.com/dperson/openvpn-client/blob/master/openvpn.sh`, if you have questions about the syntax of the auth line/file.

NOTE: I haven't tested this, please be warned that Window, Unix/Linux, and OSX all use different EOL (End Of Line) encodings, if you don't know what I'm talking about, just know that if you edit the files on Windows or OSX you may run into unexpected problems with files where the syntax looks perfect.

NOTE 2: I selected the current method because believe it or not, it was the simplest reliable way I could think of. Almost all of the '*.ovpn' file stays the same in 99% of cases, with the exception of the servername, and here where we want to specify a file that has the username/password.

Hope this helps.
