### ISSUE TITLE
Is it possible to modify firewall rules on startup?

### ISSUE THREAD

**Issue by dmp1ce** [dperson/openvpn-client#11]
I want to allow access to transmission on port 9091 but other than that, I want everything to go through openvpn. Is it possible to open that port on starting the openvpn container?

**Comment by dmp1ce** [comment]
I figured out that I can run `docker exec $cid iptables -I OUTPUT 6 -p tcp -m tcp --dport 9091 -j ACCEPT` after the container has started, but I would rather have iptables set to allow 9091 when the container starts.

**Comment by LouisLang** [comment]
Can you use nginx to proxy the connection to 9091?

    sudo docker run --name bit --net=container:vpn -d dperson/transmission
    sudo docker run --name web -p 80:80 -p 443:443 --link vpn:bit \
        -d dperson/nginx -w "http://bit:9091/transmission;/transmission"

On a similar note, does anyone know if it's possible to proxy multiple containers with one nginx container? I was able to do this using the official nginx container, but not the aforementioned one.

Something like:

    sudo docker run --name web -p 80:80 -p 443:443 --link vpn:bit --link vpn:nzb -d dperson/nginx -w "http://bit:9091/transmission;/transmission" -w "http://nzb:6789;/nzbget"

would be nice...

**Comment by dmp1ce** [comment]
The proxy doesn't help because the firewall is blocking port 9091 from even the proxy from accessing.

**Comment by dmp1ce** [comment]
@LouisLang You can try [nginx-proxy](https://github.com/jwilder/nginx-proxy). You'll have to specify VIRTUAL_HOST and VIRTUAL_PORT for each of the containers you are proxying through.

**Comment by LouisLang** [comment]
@dmp1ce I'll take a look at nginx-proxy, it looks to be exactly what I need. Thanks!

**Comment by dperson** [comment]
@dmp1ce you can actually connect to something running using my openvpn container's firewall rules, the filtering all takes place in the `OUTPUT` table. The real issue is if you're not on the local network, it's routing table will send you out the VPN connection. Which will result in one of two scenarios:

 * It will make it to the VPN provider's router with a destination reserved for an internal network and not get where it should go
 * It will get routed to the destination, but the second part of the 3-part TCP handshake will come from a different IP address than it was requested from, and be discarded

@LouisLang and @LouisLang I am currently using dperson/nginx to proxy for multiple services simultaneously. The [README](https://github.com/dperson/openvpn-client#local-network-access-to-services-connecting-to-the-internet-through-the-vpn) covers how I'm using it with transmission, but I'm running 5 more web proxies behind it, with just a `-w` command line option per container.

**Comment by dmp1ce** [comment]
@dperson You are right. I can connect just fine through the proxy. I guess I didn't give openvpn enough time to connect when I tested last night. Thank you for you explaining that to me.

Maybe an example would help with multiple services proxied. It isn't clear to me how it would work, but at the moment I'm only proxying one service which is transmission.

**Comment by LouisLang** [comment]
@dperson I assumed that I could add an additional container using the `-w` option, but I could've sworn it failed when I tried that. I'll give it another go! Thanks for the vpn container, it works great!

**Comment by dperson** [comment]
@dmp1ce sure I'll add a multiple service example to the documentation, good suggestion.

@LouisLang if you want to be able to specify it by the `--name` that you supply, then yes you'll need the `--link` option as well. I'm pretty sure that with docker 1.10 (to be released relatively soon now), a local DNS resolver will be included, so that it may no longer be needed just to simplify host names.
