### ISSUE TITLE
Issues connecting with VERIFY_ERROR

### ISSUE THREAD

**Issue by illusaen** [dperson/openvpn-client#163]
Hello,

I'm trying to attach to a PIA server on my Raspberry Pi but having issues. I didn't screenshot the whole command; left out the -v server;user;pw out for privacy purposes.

![dockerrun](https://user-images.githubusercontent.com/13263478/49348390-25c2de80-f673-11e8-8965-fe8e8bbafbcd.jpg)
![dockerlogs](https://user-images.githubusercontent.com/13263478/49348393-29566580-f673-11e8-9912-52d0a6bf5054.jpg)

Appreciate any help you can give.

**Comment by dperson** [comment]
First it's easier to copy the text from the console and paste it in. You can replace your username and password in the command to keep them private. In I think the very last ticket, there was an issue with the server name though, so I'd appreciate that being included as well.

You didn't include all the logs from the docker container, so I'm not sure. But think that it's not finding the certificate from PIA. Can you paste (as text please) an `ls -Al /home/pi/usr/dock/vpn` from your raspberry pi?

**Comment by illusaen** [comment]
I'm actually connecting via ssh instead of vnc now, so here are the actual logs, run command, and list of files in vpn folder:

`Mon Dec  3 01:40:08 2018 OpenSSL: error:14007086:SSL routines:CONNECT_CR_CERT:certificate verify failed
Mon Dec  3 01:40:08 2018 TLS_ERROR: BIO read tls_read_plaintext error
Mon Dec  3 01:40:08 2018 TLS Error: TLS object -> incoming plaintext read error
Mon Dec  3 01:40:08 2018 TLS Error: TLS handshake failed
Mon Dec  3 01:40:08 2018 SIGUSR1[soft,tls-error] received, process restarting
Mon Dec  3 01:40:18 2018 TCP/UDP: Preserving recently used remote address: [AF_INET]185.210.218.101:1194
Mon Dec  3 01:40:18 2018 UDP link local: (not bound)
Mon Dec  3 01:40:18 2018 UDP link remote: [AF_INET]185.210.218.101:1194
Mon Dec  3 01:40:18 2018 VERIFY ERROR: depth=1, error=self signed certificate in certificate chain: C=US, ST=OH, L=Columbus, O=Private Internet Access, CN=Private Internet Access CA, emailAddress=secure@privateinternetaccess.com
`

`docker run -it --cap-add=NET_ADMIN --device /dev/net/tun --name vpn \
  -v /home/pi/usr/dock/vpn/:/vpn -d dperson/openvpn-client:armhf -f "" \
  -v 'ro.privateinternetaccess.com;USERNAME;PASSWORD'
`

`crl.rsa.2048.pem  .firewall  .firewall6  vpn-ca.crt  vpn.cert_auth  vpn.conf`

Note: I tried the docker with copying over all of the Romania.ovpn file to vpn.conf as well as with the default vpn.conf that was created.

**Comment by dperson** [comment]
**NOTE**: I edited your reply to include the markdown code block formatting. You should also have a link right under the edit box with the text "Styling with Markdown is supported", that will take you to a guide.

Sorry for the slow reply, I opened this on a laptop I don't use on a daily basis. I think the issue you're seeing is 2 different issues:

1. When you use the above method, you're not setting the port (final argument after password), and PIA uses different ports than the default 1194 (they left the legacy now insecure crypto settings in place on that port). Try: `-v 'ro.privateinternetaccess.com;USERNAME;PASSWORD;PORT'`, where you can find the correct port by looking in the Romania.ovpn file.
1. When you use the Romania.ovpn file, it doesn't have a method of putting your username and password into a file so that openvpn can authenticate to the VPN server. Look into the openvpn.sh file that I add to the container to see how to add authentication to the one provided by them.
