### ISSUE TITLE
What changed in July 2019? Previously working system stopped working

### ISSUE THREAD

**Issue by DavidRedstone** [dperson/openvpn-client#204]
Hi,

What changed in July 2019? My previously working Ubuntu 19.04 system stopped working. I use docker-compose, version 2. I have a deluge container using your vpn container (connected to NordVPN, using an auth.txt file for credentials), and also have sonarr, radarr, jackett, portainer, and plex. This setup has been working for many, many months, until recently.

What stopped working:
- Containers can't talk to each other anymore, so the system doesn't do anything it is supposed to.

If I remove your vpn container from my docker-compose.yml, everything works as expected:
- sonarr and radarr can talk to deluge and jackett     (this, by using the container name)
- jackett can talk to torrent indexers

This, of course, means no vpn, so I then installed Nordvpn directly on my Ubuntu 19.04 machine, and then ran my compose file 
- Everything works as expected, and over vpn.

So something changed in the vpn container recently that means it connects to nordvpn but communication between containers is killed. I also keep seeing iptables errors with 'docker-compose up -d' in Ubuntu, that I did not see before. 

Bonus issue:
This one is not new. When I 'docker-compose down', I lose network connectivity until I reboot. I never figured out how to fix that. It is all to do with the vpn container.

I've attached my docker-compose.yml file (as .txt) - this setup has been working flawlessly since mid 2018, and only recently stopped working. I even wiped my computer and clean installed Ubuntu and docker, only to see the same new issues. It took me a week to isolate the vpn container (or its interaction with the host) as the problem.

Any ideas how to fix this? For now the workaround is not to use a vpn container.

Cheers
Dave

[docker-compose.yml.txt](https://github.com/dperson/openvpn-client/files/3439008/docker-compose.yml.txt)

**Comment by dperson** [comment]
You have the VPN container using your hosts network... that was never an expected or supported configuration. The aim was to create a VPN connection inside a running container and then have other containers use it's network stack...

There's no need to have a container manage your hosts VPN, just do that on the host itself...

IE drop the following from `vpn:`
```
    network_mode: host
```

Longer explanation, there are evidently some VPN providers that were forwarding all traffic straight to the clients, IE allowing internet traffic in. The users of both those VPNs and my container discovered it and asked to have the firewall lock things down a lot tighter, so that's why the change was made. You can either disable the firewall it must have been enabled at some point, though I don't see it in your current `docker-compose.yml` by deleting the `.firewall` and/or `.firewall6` files from the path that you mount the `/vpn` volume from, or add `-p 8112` to the `command:` section.
