### ISSUE TITLE
`-m owner` iptables rule rejected on certain hosts

### ISSUE THREAD

**Issue by bjeanes** [dperson/openvpn-client#25]
I don't have a perfect mental model of Docker and its network stack, especially with regard to iptables, so apologies if this doesn't make sense.

Running this image with `-f` on my local machine seems to work great. However, when I run it on my (Synology) host, the following is output:

```
iptables: No chain/target/match by that name.
iptables: No chain/target/match by that name.
```

Upon closer inspection, these two lines are being thrown by the two `-m owner` rules inserted into iptables.

My naive assumption is that the image should work the same regardless of host. I'm guessing that since a Docker container is using the host system's kernel, the behaviour here will differ by host.

I guess a parameter to revert to pre-a0495b5618560d106942fc81e0577122e88836be behaviour of fire walling by port could be an option. What do you think?

**Comment by dperson** [comment]
I'm 99% sure that if it's available the main system should auto-load the module when you try to access it (confirmed working on my system). The `/boot/config*` file (matching my kernel version) has `CONFIG_NETFILTER_XT_MATCH_OWNER=m` in it so I have the module available. My guess is that Synology didn't build it...

Regardless, requiring someone to rebuild their kernel so that the firewall in their docker container will work is ridiculous. I've just added a workaround that should take care of things (if you use the default `1194` openvpn port at least). It's not quite as graceful, but it's a decent fallback. Pull the latest image, and see if it doesn't work on your Synology.
