### ISSUE TITLE
Firewall question

### ISSUE THREAD

**Issue by JustTom2** [dperson/openvpn-client#289]
I think this results in a vpn container configured with firewall blocking everything if tunnel down, with ports open and routing local network (using vpn.conf and login.conf in vpn volume). How can I test the firewall is working as expected? i.e. kill the vpn tunnel while the container is running? 

Additionally does the firewall block incoming ports from the vpn tunnel or does it trust the vpn provider to block those ports? I would like access to access services from containers connected to the vpn containers from lan only.

sudo docker run -dit \\
	--name vpn \\
	--cap-add=NET_ADMIN \\
	--device /dev/net/tun \\
    	--dns 1.1.1.1 \\
        -p 9091:9091 \\
	-p 80:80 \\
        -v /tmp/vpn:/vpn \\
	dperson/openvpn-client -f "" -r 192.168.1.0/24

**Comment by dperson** [comment]
Testing it is easier if you just don't have it start the VPN in the first place, try:
'''
sudo docker run --rm -it \
--dns 1.1.1.1 \
-p 9091:9091 \
-p 80:80 \
-v /tmp/vpn:/vpn \
dperson/openvpn-client -f "" -r 192.168.1.0/24 bash
'''
You'll have a shell with the firewall but no VPN.

That is the point of the firewall configuration, to only allow DNS and the VPN itself to connect out to the internet unless it's through the VPN.

It blocks inbound traffic from the VPN as well. The only traffic allowed in by default is the docker local network and the loopback device. The `-r` also allows the specified network, though it doesn't / can't add a route to the systems on your network so that they know how to connect directly (that's well past the scope of what I'm going to support).
