### ISSUE TITLE
Does the docker container have a killswitch?

### ISSUE THREAD

**Issue by mmn01-sky** [dperson/openvpn-client#368]
In the title really. Should the vpn connection die for whatever reason, does the container block outbound traffic to the internet and prevent anything going over the unsecured network?

**Comment by whiteowl3** [comment]
Directly from page one of the documentation:

`-f '[port]' Firewall rules so that only the VPN and DNS are allowed to`
`                send internet traffic (IE if VPN is down it's offline)`
`                optional arg: [port] to use, instead of default`
                
 or with a compose file:

`    environment:`
`      - FIREWALL='' #(note that this is two single quotes not a double)`

note that using a read-only file system inside the container will prevent configuration of your dns servers and risk leaking dns requests.
