### ISSUE TITLE
Expose Squid proxy and use vpn network

### ISSUE THREAD

**Issue by McGriddle** [dperson/openvpn-client#42]
Is there a way to setup a squid proxy such that it uses the vpn container and exposes ports for access to the host?  From what I've found (and tried), using squid reverse proxied with nginx doesn't work so I'm wondering if there is another way.

**Comment by dperson** [comment]
That's what the `-r` option and `ROUTE` environment variable were put in for. They allow you to configure (one or more) route(s) back from the docker container's network to your actual network. Otherwise, return packets go out the VPN, and never get back to your systems.

**NOTE**: If you mis-configure your proxy (or other application) you can allow unrestricted access from the internet to your network.

**Comment by dperson** [comment]
That's what the `-r` option and `ROUTE` environment variable were put in for. They allow you to configure (one or more) route(s) back from the docker container's network to your actual network. Otherwise, return packets go out the VPN, and never get back to your systems.

**NOTE**: If you mis-configure your proxy (or other application) you can allow unrestricted access from the internet to your network.
