### ISSUE TITLE
Explain docker-compose.yml

### ISSUE THREAD

**Issue by joshjordan** [dperson/openvpn-client#49]
I'm so excited to see that you added a `docker-compose.yml`. Can you explain exactly what the purpose of each service in the cluster? It looks like `service1` will have VPN access, but `web` will not. Is that right? What does `web` do with `service1`?

Thanks for your effort on this!

**Comment by dperson** [comment]
Good point, I'll add it as a comment to the template file too. Please let me know if you see anything that should be fixed in the following:

The docker network is a separate range from the range your physical devices are on. When they're connected to the VPN and you send a request to them, it's not on their local network so the reply goes out the new default route of the VPN... which being on the internet doesn't have access to your private network on your LAN. Which means that you can't access container services running with the VPN container providing their network.

The web container *is* on the same docker network as the servce1, so routing between containers works seamlessly, and it will talk to your local network.
