### ISSUE TITLE
As Gateway for specified network

### ISSUE THREAD

**Issue by iGlaedr** [dperson/openvpn-client#62]
Hi 

Is it possible to run the OpenVPN Client and add static routes to the default gateway to the openvpn client for the Netowrks which are avileble on the Open VPN Server Site.

Example:
Open VPN Server XYZ.ch
Open VPN Server Subnets 192.168.1.0/24 10.10.10.0/24
Open VPN Client is connected to the Server XYZ.ch (Routed Tunnel)
Default Gateway in Client Subnet 192.168.1.0/24 to openvpn-client
Default Gateway in Client Subnet 10.10.10.0/24 to openvpn-client

thank you in advance
iGlaedr

**Comment by dperson** [comment]
If I understand your request, that's beyond the scope of what I'm doing here. It requires an openvpn config that doesn't route all traffic across the VPN. I've set it up before for my use (not in a container), and it's a PitA. I'd recommend using this VPN container, and instead of using it's network stack for the second container, just add routes for the CIDR ranges that you want to the VPN container's IP. Please let me know if I'm misunderstanding, or wasn't clear (I know I need some coffee).
