### ISSUE TITLE
iptables errors with firewall-option

### ISSUE THREAD

**Issue by jozemujo** [dperson/openvpn-client#77]
Hi David,

It's great that recently you made it possible to specify a port for the firewall. My VPN setup - with an ovpn-config file in /vpn/ - uses port 53/udp for connections.

Using `-f 53` produces this iptables error in the docker logs:

```
iptables v1.6.0: invalid port/service `53' specified

Try `iptables -h' or 'iptables --help' for more information.

iptables v1.6.0: Port "53" does not resolve to anything.
```

`docker exec vpn iptables -S` gives me the following output:

```
-P INPUT ACCEPT
-P FORWARD ACCEPT
-P OUTPUT DROP
-A OUTPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A OUTPUT -o lo -j ACCEPT
-A OUTPUT -o tap0 -j ACCEPT
-A OUTPUT -o tun0 -j ACCEPT
-A OUTPUT -d 172.17.0.0/16 -j ACCEPT
-A OUTPUT -p udp -m udp --dport 53 -j ACCEPT
```

I've also tried other values with `-f` but these errors still occur. Could you please shed some light on it?

Thanks,
Jože

**Comment by dperson** [comment]
@jozemujo you shouldn't have to provide more than `-f ""` to setup the firewall. Normally the startup script will figure out the port needed from your VPN config.

There was a user with a strange VPN vendor provided OpenVPN config file, my script failed to parse it. For them, I added the option to provide the port manually. It's been a real source of annoyance / confusion since then. I'd revert it, but that would just break everyone (again) that has updated their startup to pass in the `""` argument to `-f` *sigh*.
